version: '3.4'
services:
  logic:
    build:
      context: ../../logic
      target: final
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_GROUP: users
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
    networks:
      - postgres
      - kafka
  command:
    build:
      context: ../../command
      target: final
    ports:
      - 5050:8080
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_GROUP: command
    networks:
      - kafka
  projector:
    build:
      context: ../../projector
      target: final
    environment:
      KAFKA_SERVERS: kafka:9092
      KAFKA_GROUP: projector
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
    networks:
      - kafka
      - postgres
  query:
    build:
      context: ../../query
      target: final
    ports:
      - 5060:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: commander
      POSTGRES_PASSWORD: TFgvT3Pb3bWEhXKAfgMk63bo
      POSTGRES_DB: commander
    networks:
      - postgres
networks:
  kafka:
    external:
      name: kafka
  postgres:
    external:
      name: postgres
